/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "LibraryModule"
 * 	found in "schema/libraryModule.asn1"
 */

#ifndef	_BoardGames_H_
#define	_BoardGames_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BoardGame;

/* BoardGames */
typedef struct BoardGames {
	A_SEQUENCE_OF(struct BoardGame) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BoardGames_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BoardGames;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BoardGame.h"

#endif	/* _BoardGames_H_ */
#include <asn_internal.h>
