/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "LibraryModule"
 * 	found in "schema/libraryModule.asn1"
 */

#ifndef	_BoardGame_H_
#define	_BoardGame_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BoardGame */
typedef struct BoardGame {
	long	*id	/* DEFAULT NULL */;
	OCTET_STRING_t	*name	/* DEFAULT NULL */;
	OCTET_STRING_t	*desc	/* DEFAULT NULL */;
	long	*min_players	/* DEFAULT NULL */;
	long	*max_players	/* DEFAULT NULL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BoardGame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BoardGame;

#ifdef __cplusplus
}
#endif

#endif	/* _BoardGame_H_ */
#include <asn_internal.h>
